Optimized symlink to package matching
ajgarlag/AjglComposerSymlinker pull request #4
Opened 2017-11-23 15:55 UTC by InfopactMLoos

Instead of looping through all packages to see if they have a matching symlink defined in extra I switched it around and search a package for each defined symlink. This improves the speed, especially when having a big dependency list. Your defined symlinks are likely less in numbers then your defined packages ;)

2017-11-24 07:10 UTC, ajgarlag requested changes
Good catch! Rename the `$symlink` variable to `$symlinkDefinitions` and I will merge it ASAP

2017-11-24 07:10 UTC, ajgarlag commented on src/ScriptSymlinker.php
> +        foreach ($symlinks as $packageName => $symlink) {
Please, rename `$symlink` to `$symlinkDefinitions`

2017-11-27 12:05 UTC, InfopactMLoos commented
Ok I changed the variable name

2017-11-27 12:49 UTC, ajgarlag approved these changes

2017-11-27 12:50 UTC, merged